### ISSUE TITLE
Update examples to show off cool new features

### ISSUE THREAD

**Issue by tdmorello** [BiAPoL/napari-crop#10]
Once the multi crop feature is in action, we should update the examples in the README!

**Comment by haesleinhuepf** [comment]
Definitely @tdmorello ! Do you have a cool example image that you could share? Something more impressive than blobs.tif where you hold the copyright? (-:

**Comment by tdmorello** [comment]
I was testing on scikit's cells3d -- would that be ok?

**Comment by haesleinhuepf** [comment]
Sure! :-)
