### ISSUE TITLE
make crop_region part of the public API

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-crop#21]
Hi all,

does anybody see issues if we make `crop_region` part of the public API?

E.g. like this:
```
from napari_crop import crop_region
```

We could then use it from scripts as discssed in [this thread](https://forum.image.sc/t/napari-how-can-i-see-the-code-of-what-i-do-in-gui/62885/9).

Let me know what you think! If there are no concerns, I would just open the API.

Best,
Robert

**Comment by zoccoler** [comment]
I think that would be the way to go.
