### ISSUE TITLE
Cropped ellipses sometimes show a black line of pixels

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/napari-crop#8]
I have noticed that, for certain ellipses, the following cropped image is returned.
This behavior is inconsistent: the line appears or not depending on where the ellipse is drawn.

![ellipse_bug](https://user-images.githubusercontent.com/26173597/147571223-8e61114b-9ada-466e-a23a-46f173cd4493.png)

**Comment by tdmorello** [comment]
@zoccoler thanks for finding this -- I'll look into it. I suspect it has something to do with rounding ellipse vertices.

**Comment by haesleinhuepf** [comment]
Hi all,

I'm reopening this issue because I just saw it in the currently released version.

Best,
Robert

**Comment by zoccoler** [comment]
It seems like a bug in napari. I let the developers aware by creating an [issue there](https://github.com/napari/napari/issues/4075#issue-1128174509).

**Comment by zoccoler** [comment]
I fixed the bug in napari, so I am closing this.
